# These settings are not supported on stable Rust, and are ignored by the ninja
# build script - to use them you need to run 'cargo +nightly fmt'
group_imports = "StdExternalCrate"
imports_granularity = "Item"
imports_layout = "Vertical"
wrap_comments = true
