dist: xenial
language: python
os: linux
install:
  - sudo apt-get update
  - sudo apt-get install portaudio19-dev npm

jobs:
  include:
    - python: 3.6
      script: make build && make -j 4 test lint pytype
    - python: 3.7
      script: make build && ./tools/typecheck-setup.sh && make -j 4 check

notifications:
  email:
    if: branch = "master"
    recipients:
      - secure: "h6YYuhqlPDGVWCER46e3uVexhwUMAyvXz34XHRRm/2eH1CGxVX5zewlI/BzMYiukUt9nRvXD3v5V2YQj9Y3eLdP7Gx1Yo6K51biipP9OE2vrLusXwVbJFJCOdUuzMvs4bZEY+vmi5q25vkOiEYokkvRw/CM+zWvWczN9GLi7tiD9qvP5weg3aWfT4yTLGZG0aZpK9uM93LlBkJI9us6QcR5ukhpR8k69RKn46DhueeuXQ53yhcFwUVxUxwFWWmMWqs1Hh4uv2yXhBNqyZ0OoQfSalktS4SZvKMFBIVk/D7aM9AN/KV0ieY0xrOGWspXbp7MEgEcGomMow4zSUDgfLloVLIHERkte0waQC5MJkD5BFYkMzcNWw3UbYvQagizEBXz3086Eh8ZpfgRTkKb4K6BkcsdfV8EwqP+UxngbBq9dp9hfkcUCgqbq/5bJFWY3ilgWLh2Rx/HsvNFO3yCNiernEqamAWWDSt/+G13N+noP/45ukD/zjgq7Fo4bISoJ/F2KLmOLT4Xa4AtF0C3Y+6hS5yiVvXYKBPQ7pvi1BXCPFFGjG0X7rfy9j+gYWlvzwXqPUC+XF4aAIhwnnxzSNjuiaM0NkSKwHDFqc7FlwYXYEFw/NHeWbKF0Dk7n8lbrUOq14E7q+9K8mKtgrGJbaFTGVNtEQZpN/rhJO/9tslM="
