language: python
python:
  - "3.5"
  - "3.6"
install: 
  - sudo apt-get update
  - sudo apt-get install portaudio19-dev
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls

script: nosetests ./tests --with-coverage --cover-package=./anki
