[project]
name = "anki-dev"
version = "0.0.0"
description = "Local-only environment"
requires-python = ">=3.9"
classifiers = ["Private :: Do Not Upload"]

[dependency-groups]
dev = [
  "black==24.8.0", # temporary pin during uv migration
  "isort",
  "mypy==1.11.2", # temporary pin during uv migration
  "mypy-protobuf",
  "pylint",
  "pytest",
  "PyChromeDevTools",
  "colorama", # for isort --color
  "wheel",
  "hatchling", # for type checking hatch_build.py files
]

[project.optional-dependencies]
sphinx = [
  "sphinx",
  "sphinx_rtd_theme",
  "sphinx-autoapi",
]

[tool.uv.workspace]
members = ["pylib", "qt"]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
