[package]
name = "anki_i18n_helpers"
version = "0.0.0"
authors = ["Ankitects Pty Ltd and contributors"]
edition = "2021"
license = "AGPL-3.0-or-later"
description = "Helpers for Anki's i18n system"

[lib]
name = "anki_i18n_helpers"
path = "src/lib.rs"

# After updating anything below, run ../cargo/update.py

[dependencies]
fluent-syntax = "0.11.0"
lazy_static = "1.4.0"
regex = "1.6.0"
serde_json = "1.0.85"
walkdir = "2"
workspace-hack = { version = "0.1", path = "../../tools/workspace-hack" }
