[project]
name = "anki-release"
version = "0.1.3"
description = "A package to lock Anki's dependencies"
requires-python = ">=3.9"
dependencies = [
  "anki==24.6",
  "aqt==0.1.2",
  "anki-audio==0.1.0 ; sys_platform == 'darwin' or sys_platform == 'win32'",
  "attrs==25.3.0",
  "beautifulsoup4==4.12.3",
  "blinker==1.9.0",
  "certifi==2025.4.26",
  "charset-normalizer==3.4.2",
  "click==8.1.8 ; python_full_version < '3.10'",
  "click==8.2.1 ; python_full_version >= '3.10'",
  "colorama==0.4.6 ; sys_platform == 'win32'",
  "decorator==5.2.1",
  "distro==1.9.0 ; sys_platform != 'darwin' and sys_platform != 'win32'",
  "flask==3.1.1",
  "flask-cors==6.0.0",
  "idna==3.10",
  "importlib-metadata==8.7.0 ; python_full_version < '3.10'",
  "itsdangerous==2.2.0",
  "jinja2==3.1.6",
  "jsonschema==4.24.0",
  "jsonschema-specifications==2025.4.1",
  "markdown==3.8",
  "markupsafe==3.0.2",
  "mock==5.2.0",
  "orjson==3.10.18",
  "pip-system-certs==4.0",
  "protobuf==6.31.1",
  "psutil==7.0.0 ; sys_platform == 'win32'",
  "pyqt6==6.8.0",
  "pyqt6-qt6==6.8.1",
  "pyqt6-sip==13.10.2",
  "pyqt6-webengine==6.8.0",
  "pyqt6-webengine-qt6==6.8.1",
  "pysocks==1.7.1",
  "pywin32==310 ; sys_platform == 'win32'",
  "referencing==0.36.2",
  "requests==2.32.3",
  "rpds-py==0.25.1",
  "send2trash==1.8.3",
  "soupsieve==2.7",
  "types-click==7.1.8",
  "types-decorator==5.2.0.20250324",
  "types-flask==1.1.6",
  "types-flask-cors==6.0.0.20250520",
  "types-jinja2==2.11.9",
  "types-markdown==3.8.0.20250415",
  "types-markupsafe==1.1.10",
  "types-orjson==3.6.2",
  "types-protobuf==6.30.2.20250516",
  "types-pywin32==310.0.0.20250516",
  "types-requests==2.32.0.20250602",
  "types-waitress==3.0.1.20241117",
  "types-werkzeug==1.0.9",
  "typing-extensions==4.14.0",
  "urllib3==2.4.0",
  "waitress==3.0.2",
  "werkzeug==3.1.3",
  "wrapt==1.17.2",
  "zipp==3.23.0 ; python_full_version < '3.10'",
]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# hatch throws an error if nothing is included
[tool.hatch.build.targets.wheel]
include = ["no-such-file"]
